services:
    _defaults:
        autowire: true
        autoconfigure: false
        public: false

    Disjfa\MapsBundle\:
        resource: './../../*'
        exclude: './../../{Entity,Migrations,Tests}'

    Disjfa\MapsBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Disjfa\MapsBundle\Security\:
        resource: './../../Security/*'
        tags: ['security.voter']

    Disjfa\MapsBundle\Menu\MapsMenuListener:
        autowire: true
        tags:
        - { name: 'kernel.event_listener', event: 'site.menu_configure', method: 'onMenuConfigure', priority: -50 }
